version: '3.8'

services:
  # Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hr_oracle_db
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/OraclePassword123@//localhost:1521/XE", "@/docker-entrypoint-initdb.d/health_check.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: hr_opensearch
    environment:
      - cluster.name=hr-opensearch-cluster
      - node.name=hr-opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - hr_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # OpenSearch Dashboards
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: hr_opensearch_dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - hr_network
    depends_on:
      opensearch:
        condition: service_healthy

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: hr_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # HR AI Assistant Application
  hr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_ai_assistant
    ports:
      - "8000:8000"
    environment:
      - ORACLE_HOST=oracle-db
      - ORACLE_PORT=1521
      - ORACLE_SERVICE_NAME=XE
      - ORACLE_USERNAME=hr_user
      - ORACLE_PASSWORD=hr_password
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
    volumes:
      - ./uploads:/app/uploads
      - ./documents:/app/documents
      - ./logs:/app/logs
    networks:
      - hr_network
    depends_on:
      oracle-db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Nginx (for production)
  nginx:
    image: nginx:alpine
    container_name: hr_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - hr_network
    depends_on:
      - hr-app
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local
  opensearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  hr_network:
    driver: bridge